Repository WildCodeSchool/202209-orleans-php-project-makesense, pull requests merged in 2022-12, with the labels that each got.

#40 first PR
  assets/app.js
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/logo-makesense.png
  assets/styles/_theme.scss
  assets/styles/_wcs.scss
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#69 S01US38- navbar
  .env
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  assets/styles/app.scss
  templates/_navbar.html.twig
  templates/base.html.twig
Labels: Reviewed

#73 Sp01 us01 page Register
  assets/app.js
  assets/styles/_theme.scss
  assets/styles/app.scss
  assets/styles/register.scss
  config/packages/security.yaml
  config/packages/translation.yaml
  migrations/Version20221213162253.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  templates/registration/register.html.twig
Labels: Reviewed, Corrections done

#74 made the pdd creation page
  assets/styles/app.scss
  assets/styles/decisionCreation.scss
  config/packages/twig.yaml
  migrations/Version20221215110429.php
  src/Controller/DecisionCreationController.php
  src/Entity/Decision.php
  src/Form/DecisionCreationType.php
  src/Repository/DecisionRepository.php
  templates/decision_creation/index.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#87 fixed the navbar blank space on pages
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  templates/_navbar.html.twig
Labels: Reviewed

#76 US22- titre décisions et lien ancre
  assets/styles/_theme.scss
  assets/styles/home.scss
  composer.json
  composer.lock
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#95 US52 - made button creation for navbar and linked paths
  templates/_navbar.html.twig
Labels: Reviewed

#93 S01 us23 see all decision homepage
  assets/images/jane-doe.jpg
  assets/styles/_theme.scss
  composer.json
  composer.lock
  migrations/Version20221213162253.php
  src/Controller/HomeController.php
  src/DataFixtures/DecisionFixtures.php
  templates/base.html.twig
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Conflict resolved

#92 Dev->main #1
  .env
  assets/app.js
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/jane-doe.jpg
  assets/images/logo-makesense.png
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/decisionCreation.scss
  assets/styles/home.scss
  assets/styles/register.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  migrations/Version20221213162253.php
  migrations/Version20221215110429.php
  package.json
  src/Controller/DecisionCreationController.php
  src/Controller/HomeController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/DecisionFixtures.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Form/DecisionCreationType.php
  src/Form/RegistrationFormType.php
  src/Repository/DecisionRepository.php
  src/Repository/UserRepository.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/components/_decisionCards.html.twig
  templates/decision_creation/index.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#127 Fix- navbar
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  assets/styles/home.scss
  templates/_navbar.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#110 Fix page login
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#128 Fix alignment of all the titles, added hover for the cards and the nav titles.
  assets/styles/_theme.scss
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: Reviewed
