Repository WildCodeSchool/202209-orleans-php-project-makesense, pull requests merged in 2023-01, with the labels that each got.

#109 S01US41 - Page vue d'une décision.
  assets/images/icons/Vectororga.svg
  assets/images/icons/Vectorrisk.svg
  assets/images/icons/Vectorthumbup.svg
  assets/images/icons/decisiontxt.svg
  assets/images/icons/finaldecisiontxt.svg
  assets/images/icons/firsstdecisiontxt.svg
  assets/images/icons/person.svg
  assets/images/jane-doe.jpg
  assets/styles/app.scss
  assets/styles/decisionView.scss
  src/Controller/DecisionController.php
  templates/components/_decisionCards.html.twig
  templates/decisions/decisionView.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#131 S02 us17 searchbar
  src/Controller/HomeController.php
  src/Form/DecisionSearchType.php
  src/Repository/DecisionRepository.php
  templates/home/index.html.twig
Labels: Reviewed

#132 changed user placeholder
  templates/_navbar.html.twig
  templates/components/_decisionCards.html.twig
Labels: Reviewed

#135 S02US51 - decisions finished soon
  src/Controller/DecisionController.php
  src/Controller/DecisionCreationController.php
  src/Controller/HomeController.php
  src/Repository/DecisionRepository.php
  templates/home/index.html.twig
Labels: Reviewed

#134 fixed bg color of viewDecision and added navbar shadow
  assets/styles/_navbar.scss
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#141 fixed typos on homepage
  templates/home/index.html.twig
Labels: Reviewed

#138 S02US24 -added recently finished decision on homepage
  src/Controller/HomeController.php
  src/Repository/DecisionRepository.php
  templates/home/index.html.twig
Labels: Reviewed, Conflict resolved

#145 S02 us56 view decision creator
  assets/styles/decisionView.scss
  migrations/Version20230104175111.php
  src/Controller/DecisionController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Decision.php
  src/Entity/User.php
  templates/components/_decisionCards.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#149 added placeholder to decision creation form
  src/Form/DecisionCreationType.php
Labels: Reviewed

#155 S02 us48 wysiwyg editor
  assets/styles/decisionCreation.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  package.json
  src/Form/DecisionCreationType.php
  symfony.lock
  templates/decision_creation/index.html.twig
  templates/decisions/decisionView.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, Conflict resolved

#154 fixed logout and profil routes
  src/Controller/ProfileController.php
  templates/_navbar.html.twig
Labels: Reviewed, Corrections done

#158 Fix- modified the config of ckeditor
  config/packages/fos_ckeditor.yaml
Labels: Reviewed

#156 S01US43-Timeline d'une décision
  assets/images/icons/arrow2.svg
  assets/images/icons/arrow3.svg
  assets/images/icons/arrow4.svg
  assets/images/icons/arrowstart.svg
  assets/images/icons/calendar.svg
  assets/styles/decisionView.scss
  composer.json
  composer.lock
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#159 FIX- Changed the animation of the decision card
  assets/styles/_theme.scss
Labels: Reviewed

#160 Fix- fixed style of error messages and put required on inputs
  templates/login/index.html.twig
Labels: Reviewed

#161 Fix - added |raw to view decision
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#157 dev->main#4
  assets/images/icons/arrow2.svg
  assets/images/icons/arrow3.svg
  assets/images/icons/arrow4.svg
  assets/images/icons/arrowstart.svg
  assets/images/icons/calendar.svg
  assets/styles/ViewMyProfil.scss
  assets/styles/_theme.scss
  assets/styles/decisionCreation.scss
  assets/styles/decisionView.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/security.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20230104153537.php
  package.json
  public/uploads/avatar/.gitignore
  src/Controller/HomeController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/DecisionCreationType.php
  src/Form/ProfileType.php
  src/Form/RegistrationFormType.php
  symfony.lock
  templates/_navbar.html.twig
  templates/decision_creation/index.html.twig
  templates/decisions/decisionView.html.twig
  templates/login/index.html.twig
  templates/view_my_profil/_uploadImage.html.twig
  templates/view_my_profil/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#182 FIX- homepage design
  assets/styles/_theme.scss
  templates/home/index.html.twig
Labels: Reviewed

#183 FIX- fixed the position of the buttons
  templates/login/index.html.twig
Labels: Reviewed

#184 FIX- Fixed spacing of the labels register
  templates/registration/register.html.twig
Labels: Reviewed

#185 FIX- Input Size Title
  templates/decision_creation/index.html.twig
Labels: Reviewed

#197 FIX- Profil picture placeholder, added white bg and changed the css
  assets/images/icons/person.svg
  assets/styles/_theme.scss
Labels: Reviewed

#190 S03US03-See impacted employees
  assets/styles/decisionView.scss
  migrations/Version20230116091223.php
  src/Controller/DecisionController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Decision.php
  src/Entity/Interaction.php
  src/Entity/User.php
  src/Repository/InteractionRepository.php
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Corrections done

#198 securized decisionController
  src/Controller/DecisionController.php
Labels: Reviewed

#196 S03 us19 see my decisions
  src/Controller/DashBoardController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/_navbar.html.twig
  templates/dashboard/index.html.twig
Labels: Reviewed, Conflict resolved

#204 S03US04-display expert role
  src/Controller/DecisionController.php
  src/DataFixtures/InteractionFixtures.php
  src/Entity/Interaction.php
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#143 S02US11-category
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  migrations/Version20230108123103.php
  src/Controller/UserController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/Entity/Category.php
  src/Entity/Decision.php
  src/Form/UserType.php
  src/Repository/CategoryRepository.php
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed, Conflict resolved

#228 dev->main#6
  assets/images/icons/arrowstart.svg
  assets/images/icons/person.svg
  assets/styles/_theme.scss
  assets/styles/dashboardView.scss
  assets/styles/decisionView.scss
  migrations/Version20230108123103.php
  migrations/Version20230116091223.php
  src/Controller/DashBoardController.php
  src/Controller/DecisionController.php
  src/Controller/UserController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/Decision.php
  src/Entity/Interaction.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/CategoryRepository.php
  src/Repository/InteractionRepository.php
  templates/_navbar.html.twig
  templates/components/_decisionCards.html.twig
  templates/dashboard/index.html.twig
  templates/decision_creation/index.html.twig
  templates/decisions/decisionView.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  webpack.config.js
Labels: Reviewed

#227 S03 us58 add impacted employee
  assets/app.js
  assets/styles/decisionCreation.scss
  package-lock.json
  package.json
  src/Controller/DecisionController.php
  src/Entity/Decision.php
  src/Entity/Interaction.php
  src/Entity/User.php
  src/Form/DecisionCreationType.php
  src/Form/InteractionType.php
  templates/decision_creation/index.html.twig
  yarn.lock
Labels: Reviewed

#229 Fix- spacing category tag
  templates/components/_decisionCards.html.twig
Labels: Reviewed

#230 FIX- The employee section won't be displayed in mobile version
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#224 S03US60 Color of the decision view page change according to status of the decision
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  templates/components/_decisionSection.html.twig
  templates/components/_timeline.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#242 fixed too much interaction for decision fixtures
  src/DataFixtures/DecisionFixtures.php
Labels: Reviewed

#245 S04US61- Add_expert_employee
  src/Form/InteractionType.php
  templates/components/_decisionCards.html.twig
Labels: Reviewed

#256 FIX- login btn visibility
  templates/login/index.html.twig
  yarn.lock
Labels: Reviewed

#243 S04US18-See_my_impacting_decisions
  src/Controller/DashBoardController.php
  templates/dashboard/index.html.twig
Labels: Reviewed

#257 FIX- the title of the dashboard (New)
  assets/styles/_theme.scss
  assets/styles/dashboardView.scss
  templates/dashboard/index.html.twig
  webpack.config.js
Labels: Reviewed

#269 FIX- the border radius of the text editor
  assets/styles/decisionCreation.scss
Labels: Reviewed

#231 Comment the first Decision
  migrations/Version20230120092532.php
  src/Controller/DecisionController.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/Entity/Comment.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  src/Repository/InteractionRepository.php
  templates/decisions/commentView.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#249 S04US68 -edit for decisions
  assets/styles/decisionCreation.scss
  src/Controller/DecisionController.php
  src/Form/DecisionCreationType.php
  src/Form/DecisionEditionType.php
  src/Security/DecisionVoter.php
  templates/components/_decisionForm.html.twig
  templates/components/_editDecisionForm.html.twig
  templates/decision_creation/index.html.twig
  templates/decisions/decisionView.html.twig
  templates/decisions/edit.html.twig
Labels: Reviewed, Conflict resolved

#273 fix: added app user name and uploaded picture to the navbar
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  templates/_navbar.html.twig
Labels: Reviewed

#275 fix: repaired damaged Decision
  src/Entity/Decision.php
Labels: Reviewed

#276 FIX - Pages Approuved Users
  migrations/Version20230120092532.php
  src/Controller/AdminUserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/admin_user/_form.html.twig
  templates/admin_user/index.html.twig
  templates/admin_user/show.html.twig
Labels: Reviewed

#282 Fix role TedyDoe
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#284 fix: repaired broken decision form
  templates/components/_decisionForm.html.twig
Labels: Reviewed

#274 fix: added uploaded images to decision view and cards, added 2 potent…
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  templates/components/_decisionCards.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#272 S04 us08 vote before decision ending
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  migrations/Version20230125134815.php
  src/Controller/DecisionController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/Entity/Interaction.php
  src/Security/DecisionVoter.php
  src/Service/Voting.php
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#285 FIX- conditions for the decision's view
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#288 fix: added a space between firstname and lastname in navbar
  templates/_navbar.html.twig
Labels: Reviewed

#271 Send the mail for the new decision
  config/packages/mailer.yaml
  config/services.yaml
  src/Controller/DecisionController.php
  templates/email/impact.html.twig
Labels: Reviewed, Conflict resolved

#281 US42S04 - Visualization of the comments.
  assets/styles/commentView.scss
  src/Controller/DecisionController.php
  templates/components/_comment.html.twig
  templates/components/_decisionSection.html.twig
  templates/decisions/commentCreateView.html.twig
  templates/decisions/commentView.html.twig
  webpack.config.js
Labels: Reviewed, Conflict resolved

#289 Fix- admin user style
  assets/styles/_theme.scss
  templates/admin_user/_delete_form.html.twig
  templates/admin_user/_form.html.twig
  templates/admin_user/edit.html.twig
  templates/admin_user/index.html.twig
  templates/admin_user/show.html.twig
Labels: Reviewed, Corrections done

#290 FIX- Admin can have additional nav link to the list of users
  templates/_navbar.html.twig
Labels: Reviewed

#295 FIX - File DMM
  migrations/Version20230126092940.php
Labels: Reviewed

#296 FixPageMyDecision
  src/Entity/Decision.php
  templates/dashboard/index.html.twig
Labels: Reviewed

#286 FIX- Alignement of two buttons in the decision view page
  assets/styles/decisionView.scss
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#291 FIX- display navlink second and final decision
  templates/components/_decisionSection.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#297 fixed closed div
  templates/components/_decisionSection.html.twig
Labels: Reviewed

#299 Fix- Background
  templates/dashboard/index.html.twig
Labels: Reviewed

#306 S04US56 : added status on cards
  assets/styles/_theme.scss
  migrations/Version20230129195121.php
  src/Controller/DecisionController.php
  src/Controller/HomeController.php
  src/Entity/Decision.php
  src/Service/TimelineManager.php
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#315 FIX- removed the nav link under the searchbar
  templates/home/index.html.twig
Labels: Reviewed

#314 FIX- harmonized the comment creation page
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed

#302 S04US65-write_final_decision
  migrations/Version20230126092940.php
  src/Controller/DecisionController.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/Entity/Decision.php
  src/Form/DecisionEditionType.php
  src/Repository/DecisionRepository.php
  templates/components/_editDecisionForm.html.twig
Labels: Reviewed, Conflict resolved

#303 FIX - Page User
  src/Controller/AdminUserController.php
  templates/admin_user/_form.html.twig
  templates/admin_user/index.html.twig
  templates/admin_user/show.html.twig
Labels: Reviewed, Corrections done

#320 Update read me
  .env
  README.md
Labels: Reviewed

#317 FIX- New decision view
  assets/images/icons/Vectororga.svg
  assets/images/icons/Vectorrisk.svg
  assets/images/icons/bene.svg
  assets/images/icons/calendar.svg
  assets/images/icons/decisiontxt.svg
  assets/images/icons/finaldecisiontxt.svg
  assets/images/icons/firsstdecisiontxt.svg
  assets/images/icons/seecomment.svg
  assets/images/icons/title.svg
  assets/images/icons/writtingcom.svg
  assets/styles/commentView.scss
  assets/styles/decisionView.scss
  src/Controller/DecisionController.php
  src/Service/Voting.php
  templates/components/_commentFrame.html.twig
  templates/components/_decisionPart.html.twig
  templates/components/_decisionSection.html.twig
  templates/components/_headerDetails.html.twig
  templates/components/_sideBar.html.twig
  templates/components/_timeline.html.twig
  templates/components/_vote.html.twig
  templates/decisions/decisionView.html.twig
  webpack.config.js
Labels: Reviewed, Corrections done

#318 S04 us70 put decision in conflict
  assets/styles/_theme.scss
  migrations/Version20230130134358.php
  src/Controller/DecisionController.php
  src/Entity/Comment.php
  src/Form/CommentType.php
  templates/components/_decisionCards.html.twig
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed, Conflict resolved

#343 fix: added status and status color to fixtures, on decision creation …
  src/Controller/DashBoardController.php
  src/Controller/DecisionController.php
  src/Controller/HomeController.php
  src/DataFixtures/DecisionFixtures.php
Labels: Reviewed

#344 Fix- Decision View responsive
  templates/components/_headerDetails.html.twig
  templates/components/_sideBar.html.twig
Labels: Reviewed

#345 fix background size
  templates/decisions/allDecisions.html.twig
Labels: Reviewed

#347 fix - color of the button of the comment creation
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed

#351 Merci ✌️
  assets/styles/_theme.scss
  src/Controller/DashBoardController.php
  src/Controller/DecisionController.php
  src/Controller/HomeController.php
  src/DataFixtures/DecisionFixtures.php
  templates/components/_headerDetails.html.twig
  templates/components/_sideBar.html.twig
  templates/decisions/allDecisions.html.twig
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed, Dev -> Main

#350 FIx- Added a dropdown to the navbar admin
  templates/_navbar.html.twig
Labels: Reviewed

#352 fix: conditionnal avis button
  templates/components/_sideBar.html.twig
Labels: Reviewed
