Repository WildCodeSchool/202209-orleans-php-project-makesense, pull requests merged in 2023-02, with the labels that each got.

#342 Finish add ChoiceType for DecisionCreation and editDecision
  src/Form/DecisionCreationType.php
  src/Form/UserType.php
  templates/components/_decisionForm.html.twig
  templates/components/_editDecisionForm.html.twig
Labels: Reviewed, Conflict resolved

#348 fix: only impacted and expert employees can ge tin conflict in a deci…
  src/Controller/DecisionController.php
  templates/base.html.twig
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed, Conflict resolved

#354 Fix: deleted useless isApproved field
  src/Form/RegistrationFormType.php
Labels: Reviewed

#356 Fix: reworked margins for the form
  templates/login/index.html.twig
Labels: Reviewed

#358 FIX - vote bloc
  assets/styles/_theme.scss
  src/Controller/DecisionController.php
  src/Service/Voting.php
  templates/components/_vote.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#361 Fix: send decisionStatus to view
  src/Controller/DecisionController.php
Labels: Reviewed

#372 fix: made dashboard voter
  src/Controller/DashBoardController.php
  src/Security/DashboardVoter.php
Labels: Reviewed

#373 Fix - SendTheMail
  src/Controller/DecisionController.php
Labels: Reviewed

#374 fix: made voter for comments
  src/Controller/DecisionController.php
  src/Security/CommentVoter.php
Labels: Reviewed

#376 Fix - Page My Profil
  templates/decisions/commentCreateView.html.twig
  templates/decisions/decisionView.html.twig
  templates/view_my_profil/index.html.twig
Labels: Reviewed

#389 fix: changed marketing color
  src/DataFixtures/CategoryFixtures.php
Labels: Reviewed

#363 Fix comment status
  src/Controller/DecisionController.php
  templates/components/_comment.html.twig
  templates/decisions/commentCreateView.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#375 Fix: assert decision start date greater than today
  src/Entity/Decision.php
Labels: Reviewed, Corrections done

#391 Fix: added status on decision creation
  migrations/Version20230129195121.php
  src/Controller/DecisionController.php
Labels: Reviewed

#392 fix: vote bloc new status system
  templates/components/_vote.html.twig
Labels: Reviewed

#396 Dev to main
  assets/images/icons/Vectororga.svg
  assets/images/icons/Vectorrisk.svg
  assets/images/icons/Vectorthumbup.svg
  assets/images/icons/bene.svg
  assets/images/icons/finaldecisiontxt.svg
  assets/images/icons/firsstdecisiontxt.svg
  assets/images/icons/seecomment.svg
  assets/images/icons/title.svg
  assets/images/icons/writtingcom.svg
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  migrations/Version20230129195121.php
  migrations/Version20230205215532.php
  src/Controller/DashBoardController.php
  src/Controller/DecisionController.php
  src/Controller/HomeController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Decision.php
  src/Entity/Status.php
  src/Form/CommentType.php
  src/Form/DecisionCreationType.php
  src/Form/DecisionEditionType.php
  src/Form/ProfileType.php
  src/Form/RegistrationFormType.php
  src/Form/UserType.php
  src/Repository/StatusRepository.php
  src/Security/CommentVoter.php
  src/Security/DashboardVoter.php
  src/Service/AutomatedDates.php
  src/Service/StatusUpdater.php
  src/Service/TimelineManager.php
  src/Service/Voting.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/components/_comment.html.twig
  templates/components/_commentFrame.html.twig
  templates/components/_decisionCards.html.twig
  templates/components/_decisionForm.html.twig
  templates/components/_decisionPart.html.twig
  templates/components/_editDecisionForm.html.twig
  templates/components/_sideBar.html.twig
  templates/components/_vote.html.twig
  templates/decisions/commentCreateView.html.twig
  templates/decisions/decisionView.html.twig
  templates/login/index.html.twig
  templates/view_my_profil/index.html.twig
Labels: Reviewed

#309 US69S05 - Error 404 and 401 pages
  assets/styles/_theme.scss
  composer.lock
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/errorBase.html.twig
Labels: Reviewed, Conflict resolved

#399 Fix - fixed the vote section
  templates/components/_vote.html.twig
Labels: Reviewed

#400 add name tooltip
  assets/styles/decisionView.scss
  templates/components/_headerDetails.html.twig
Labels: Reviewed

#395 Favicon
  assets/images/favicon-ms.svg
  assets/images/favicoon-ms.png
  templates/base.html.twig
Labels: Reviewed, Corrections done

#403 Fix: deleted access denied on comment, fixed conflict condition
  src/Controller/DecisionController.php
Labels: Reviewed

#402 Fix: added more informatins to decision view header
  src/Controller/DecisionController.php
  templates/components/_vote.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Conflict resolved

#397 Fix - changed design of the creation decision page
  templates/components/_decisionForm.html.twig
Labels: Reviewed, Corrections done

#406 Fix- Style of the button
  templates/home/index.html.twig
Labels: Reviewed

#404 Fix-PageUsers
  assets/styles/_theme.scss
  src/Controller/ProfileController.php
  templates/components/_headerDetails.html.twig
  templates/decisions/commentView.html.twig
  templates/decisions/decisionView.html.twig
  templates/view_my_profil/profil.html.twig
Labels: Conflict resolved

#405 Fix - pictures rounded
  assets/styles/_navbar.scss
  assets/styles/decisionView.scss
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#409 fixed the header
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#408 Fix - the edit of the decision
  src/Entity/Decision.php
  src/Form/DecisionEditionType.php
  templates/components/_editDecisionForm.html.twig
Labels: Reviewed

#413 Fix the info and the size of the numbers
  templates/components/_vote.html.twig
Labels: Reviewed

#414 Fix- Class of the pictures
  assets/styles/ViewMyProfil.scss
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  templates/components/_comment.html.twig
  templates/dashboard/index.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#412 Fix: added realistic fixtures
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#415 ✌️Merci
  assets/styles/ViewMyProfil.scss
  assets/styles/_navbar.scss
  assets/styles/_theme.scss
  assets/styles/decisionView.scss
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Decision.php
  src/Form/DecisionEditionType.php
  templates/components/_comment.html.twig
  templates/components/_editDecisionForm.html.twig
  templates/components/_vote.html.twig
  templates/dashboard/index.html.twig
  templates/decisions/allDecisions.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed, Dev -> Main

#416 Fix- design of the button
  templates/decisions/commentView.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#417 Fix- the opacity in the timeline and changed a class in the vote section
  templates/components/_vote.html.twig
  templates/decisions/decisionView.html.twig
Labels: Reviewed

#418 Fix: fixtures corrections
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#419 Fix: fixed errors from w3c validator
  templates/base.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#420 Fix: less users and added final decision to création de poste symfony
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#421 Fix Trouble with the trad of the month and added a text to the conflict button
  templates/components/_headerDetails.html.twig
  templates/decisions/commentCreateView.html.twig
Labels: Reviewed

#422 Fix: added a migration file to add category in production
  migrations/Version20230208133233.php
Labels: Reviewed

#423 Fix duplicated role admin user
  src/Form/UserType.php
  templates/admin_user/edit.html.twig
Labels: Reviewed

#424 Dev to main
  migrations/Version20230208133233.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Form/UserType.php
  templates/admin_user/edit.html.twig
  templates/base.html.twig
  templates/components/_headerDetails.html.twig
  templates/components/_vote.html.twig
  templates/decisions/commentCreateView.html.twig
  templates/decisions/commentView.html.twig
  templates/decisions/decisionView.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#425 Fix new fixtures v30
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#426 Merci ✌️
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/InteractionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed, Dev -> Main
